### ISSUE TITLE
Intro to the Vault Secrets Operator

### ISSUE THREAD

**Issue by tvoran** [AdamBouhmad/SeattleHUGTalks#1]
**Talk Title:** Vault Secrets Operator

**Talk Idea, described briefly:** Just an intro to the new [Vault Secrets Operator](https://github.com/hashicorp/vault-secrets-operator) for Kubernetes. Starting with an overview of HashiCorp's Vault and Kubernetes integrations, then a walkthrough of our operator usage, then a demo if there's time.

**Your name:** Theron Voran

**Twitter username (optional):** tvoran

**Estimated Talk Length: (15-30 min please):** 15

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] August 2nd, 2023
**Future Dates are TBD based on community feedback** 

By submitting this talk, I acknowledge that:

- Submission of the talk is not a guarantee of acceptance.

**Comment by AdamBouhmad** [comment]
Hey @tvoran, thanks for your submission! I wanted to confirm that youre still available to give this talk at the August 2nd meetup?

**Comment by tvoran** [comment]
Yep, that should work for me.

**Comment by AdamBouhmad** [comment]
Awesome! Approved, I'll slot you in for the 5:15 slot on August 2nd.
