### ISSUE TITLE
Share the explorer

### ISSUE THREAD

**Issue by Ashtronaut09** [AdamBouhmad/SeattleHUGTalks#2]
**We released the explorer for TFC**

**Here's what you can do with the explorer and what we have coming up. If you'd like to give feedback on direction feel free to say something.**

**Ashley Adamson**

**@Ashleyxadamson**

**Estimated Talk Length: (15-30 min please): 10 min **

**Availability:**
Next talk

- [ ] July 28th, 2023

By submitting this talk, I acknowledge that:

- Submission of the talk is not a guarantee of acceptance.

**Comment by AdamBouhmad** [comment]
Hey @Ashtronaut09, thanks for your submission! Talk is approved!
