### ISSUE TITLE
A Brief Introduction to Hashicorp Boundary

### ISSUE THREAD

**Issue by steven-whaley** [AdamBouhmad/SeattleHUGTalks#3]
**Talk Title: A Brief Introduction to Hashicorp Boundary**

**Talk Idea, described briefly: Boundary is a secure infrastructure access management tool developed by Hashicorp to simplify the process of connecting to infrastructure such as virtual machines, containers and databases while providing enhanced security and visibility into those sessions.  This talk will cover the architecture of Boundary and how it works to secure sessions, and include a short demonstration of connecting to infrastructure resources with Boundary and viewing the session information.**

**Your name: Steven Whaley**

**Twitter username (optional):**

**Estimated Talk Length: (15-30 min please): 20 minutes**

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [X] August 2nd, 2023

**Future Dates are TBD based on community feedback** 

By submitting this talk, I acknowledge that:

- Submission of the talk is not a guarantee of acceptance.

**Comment by AdamBouhmad** [comment]
Hey @steven-whaley, thanks for your submission! Talk is approved!
