### ISSUE TITLE
Private Game server with HCP Boundary

### ISSUE THREAD

**Issue by bosorawis** [AdamBouhmad/SeattleHUGTalks#4]
**Talk Title:** [show and tell] Private Terraria server with HCP Boundary mult-hop

**Talk Idea, described briefly:**
Go over setup and demo a Game (Terraria) server running in an AWS VPC private subnet and connect to it through Boundary multi-hop. 

**Your name:** Sorawis (Bo)

**Twitter username (optional):**

**Estimated Talk Length: (15-30 min please):** 15 minutes

**Availability:**
_Please check off the dates in which you would be interested in presenting your talk:_

- [x] August 2nd, 2023

**Future Dates are TBD based on community feedback** 

By submitting this talk, I acknowledge that:

- Submission of the talk is not a guarantee of acceptance.

**Comment by AdamBouhmad** [comment]
hey @dihmuzikien, thanks for the submission! Talk is approved!
